resource "local_file" "inventory" {
  content = <<-DOC
    # Ansible inventory containing variable values from Terraform.
    # Generated by Terraform.

    dns:
      hosts: 
        nginx:
          ansible_host: ${yandex_compute_instance.nginx.network_interface.0.nat_ip_address}
          ansible_ssh_private_key_file: ~/secrets/netology

    DOC
  filename = "../ansible-dns/inventory.yml"

  depends_on = [
    yandex_compute_instance.nginx,
  ]
}
