---
nginx:
  hosts:
    nginx-01:
      ansible_host: "{{ my_domain }}"
      ansible_connection: ssh
      ansible_user: "{{ ssh_user }}"
      ansible_ssh_private_key_file: "{{ ssh_key_file }}"

wordpress:
  hosts:
    app:
      ansible_host: "{{ my_domain }}"
      ansible_port: 2010
      ansible_connection: ssh
      ansible_user: "{{ ssh_user }}"
      ansible_ssh_private_key_file: "{{ ssh_key_file }}"

gitlab:
  hosts:
    gitlab-server:
      ansible_host: "{{ my_domain }}"
      ansible_port: 2011
      ansible_connection: ssh
      ansible_user: "{{ ssh_user }}"
      ansible_ssh_private_key_file: "{{ ssh_key_file }}"
    gitlab-runner:
      ansible_host: "{{ my_domain }}"
      ansible_port: 2017
      ansible_connection: ssh
      ansible_user: "{{ ssh_user }}"
      ansible_ssh_private_key_file: "{{ ssh_key_file }}"

monitoring:
  hosts:
    monitoring-01:
      ansible_host: "{{ my_domain }}"
      ansible_port: 2012
      ansible_connection: ssh
      ansible_user: "{{ ssh_user }}"
      ansible_ssh_private_key_file: "{{ ssh_key_file }}"

mysql:
  hosts:
    db01:
      ansible_host: "{{ my_domain }}"
      ansible_port: 2015
      ansible_connection: ssh
      ansible_user: "{{ ssh_user }}"
      ansible_ssh_private_key_file: "{{ ssh_key_file }}"
      master: true
    db02:
      ansible_host: "{{ my_domain }}"
      ansible_port: 2016
      ansible_connection: ssh
      ansible_user: "{{ ssh_user }}"
      ansible_ssh_private_key_file: "{{ ssh_key_file }}"
      slave: true
